package scanner

import (
	_ "embed"
	"strings"
	"sync"
)

//go:generate go run gen_oui.go

// oui_registry.tsv is the IEEE Registration Authority's public listing of MAC
// address blocks, regenerated by gen_oui.go. IEEE asserts no copyright in it
// and places no restriction on redistribution.
//
//go:embed oui_registry.tsv
var ouiRegistryTSV string

// The three unicast block sizes IEEE assigns, in hex digits of the address.
// A block is assigned at exactly one of these sizes, and a longer assignment
// lives inside a shorter block that was subdivided, so a lookup has to try
// the most specific first or it will credit a sub-assignee's device to
// whoever holds the enclosing range.
const (
	ouiLenMAS = 9 // MA-S, 36 bits
	ouiLenMAM = 7 // MA-M, 28 bits
	ouiLenMAL = 6 // MA-L, 24 bits
)

var (
	ouiOnce  sync.Once
	ouiBlock map[string]string
)

func loadOUIRegistry() {
	ouiBlock = make(map[string]string, 54000)
	for _, line := range strings.Split(ouiRegistryTSV, "\n") {
		if line == "" || line[0] == '#' {
			continue
		}
		tab := strings.IndexByte(line, '\t')
		if tab <= 0 {
			continue
		}
		ouiBlock[line[:tab]] = line[tab+1:]
	}
}

// macHex reduces any of the usual MAC spellings to bare uppercase hex. It
// returns "" for anything that is not a full 48-bit address, because a
// partial address cannot be attributed and guessing from one is how you get
// a confident wrong answer.
func macHex(mac string) string {
	var b strings.Builder
	b.Grow(12)
	for i := 0; i < len(mac); i++ {
		c := mac[i]
		switch {
		case c >= '0' && c <= '9', c >= 'A' && c <= 'F':
			b.WriteByte(c)
		case c >= 'a' && c <= 'f':
			b.WriteByte(c - 'a' + 'A')
		case c == ':' || c == '-' || c == '.' || c == ' ':
		default:
			return ""
		}
	}
	if b.Len() != 12 {
		return ""
	}
	return b.String()
}

// registryVendor returns the organisation IEEE records as holding the block
// this address falls in, trying the most specific assignment size first.
func registryVendor(hex string) (string, bool) {
	ouiOnce.Do(loadOUIRegistry)
	for _, n := range []int{ouiLenMAS, ouiLenMAM, ouiLenMAL} {
		if org, ok := ouiBlock[hex[:n]]; ok {
			return org, true
		}
	}
	return "", false
}

// isLocallyAdministered reports whether the address was made up by the device
// rather than drawn from an assigned block. Phones and laptops randomise
// their MAC per network by default now, so this is the common case for an
// unrecognised address, not an oddity.
//
// Eighteen genuine 1980s assignments (DEC's AA-00-0x among them) predate the
// convention and do carry the bit, which is why the registry is consulted
// before this is.
func isLocallyAdministered(hex string) bool {
	first, ok := hexByte(hex)
	return ok && first&0x02 != 0
}

func hexByte(hex string) (byte, bool) {
	if len(hex) < 2 {
		return 0, false
	}
	v := 0
	for i := 0; i < 2; i++ {
		c := hex[i]
		switch {
		case c >= '0' && c <= '9':
			v = v<<4 | int(c-'0')
		case c >= 'A' && c <= 'F':
			v = v<<4 | int(c-'A'+10)
		default:
			return 0, false
		}
	}
	return byte(v), true
}
